spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scaffold
    username: root
    password: 123456





customer:
  thrift:
    server:
      port: 8090
      ipAddress: 127.0.0.1












