spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scaffold
    username: root
    password: 123456

logging:
  level:
    root: info
    org.lantern: debug
    org.springframework.boot: debug
    org.apache.thrift: debug



customer:
  thrift:
    server:
      port: 8090
      ipAddress: 127.0.0.1





